### PR TITLE
Memcached

### LINKED ISSUE #87: unique_size assertion kills gearmand start
steps to reproduce
- start `gearmand` with memcache queue
  ```bash
v1.1.15/sbin/gearmand --verbose DEBUG -p 4731 --queue-type libmemcached --libmemcached-servers 127.0.0.1:11211
```
- add some jobs without unique key
- stop `gearmand`
- start `gearmand` ends in exception: 
```text
/home/apastuchov/v1.1.15/sbin/gearmand: Could not open log file "/home/apastuchov/v1.1.15/var/log/gearmand.log", from "/home/apastuchov", switching to stderr. (No such file or directory)
  DEBUG 2017-03-21 10:37:44.094472 [  main ] THREADS: 4 -> libgearman-server/gearmand.cc:263
   INFO 2017-03-21 10:37:44.094718 [  main ] Initializing libmemcached module
   INFO 2017-03-21 10:37:44.095136 [  main ] Initializing Gear on port 4731 with SSL: false
   INFO 2017-03-21 10:37:44.095318 [  main ] Starting up with pid 17081, verbose is set to DEBUG
  DEBUG 2017-03-21 10:37:44.095657 [  main ] Method for libevent: epoll -> libgearman-server/gearmand.cc:364
  DEBUG 2017-03-21 10:37:44.095985 [  main ] Trying to listen on 0.0.0.0:4731 -> libgearman-server/gearmand.cc:646
   INFO 2017-03-21 10:37:44.096246 [  main ] Listening on 0.0.0.0:4731 (9)
  DEBUG 2017-03-21 10:37:44.096421 [  main ] Trying to listen on :::4731 -> libgearman-server/gearmand.cc:646
   INFO 2017-03-21 10:37:44.096591 [  main ] Listening on :::4731 (10)
  DEBUG 2017-03-21 10:37:44.096843 [  main ] Creating wakeup pipe -> libgearman-server/gearmand.cc:915
  DEBUG 2017-03-21 10:37:44.097017 [  main ] Creating 4 threads -> libgearman-server/gearmand.cc:378
  DEBUG 2017-03-21 10:37:44.097244 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.097476 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.097699 [  main ] Thread 1 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.097969 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.098221 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.098467 [  main ] Thread 2 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.098699 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.098979 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.099232 [  main ] Thread 3 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.099468 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.099707 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.099981 [  main ] Thread 4 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.100386 [  main ] replaying queue: begin -> libgearman-server/gearmand.cc:391
  DEBUG 2017-03-21 10:37:44.100585 [  main ] libmemcached replay start -> libgearman-server/plugins/queue/libmemcached/queue.cc:375
  DEBUG 2017-03-21 10:37:44.101303 [  main ] SUCCESS -> libgearman-server/plugins/queue/libmemcached/queue.cc:357
  DEBUG 2017-03-21 10:37:44.101583 [  main ] SUCCESS -> libgearman-server/plugins/queue/libmemcached/queue.cc:357
  DEBUG 2017-03-21 10:37:44.101819 [  main ] unique: '(null)', size: '-945361264' -> libgearman-server/plugins/queue/libmemcached/queue.cc:314
gearmand: libgearman-server/plugins/queue/libmemcached/queue.cc:316: callback_loader: Assertion `unique_size' failed.
```

[LP PR](http://bazaar.launchpad.net/~1-infe-w/gearmand/1.0/revision/806) for the issue was already declined. Any other suggestion to solve the issue?

### PR DESCRIPTION
**Pull request by p-alik**
- primary aim of the PR is to fix #87
- BTW some refactoring of libmemcached queue plugin implementation

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/97/1491395616.31/bonnyci-run-check : POST_FAILURE in 15s

**Comment by p-alik** [comment]
bonnyci link shows `File Not Found`

**Comment by SpamapS** [comment]
recheck @p-alik You can always ask for support in #bonnyci on Freenode if you can't find me. POST_FAILURE is actually a failure to post logs, so file not found is not surprising. Any time you see POST_FAILURE, you can post a comment that starts with the word 'recheck' and it will re check the patch set. Note that this comment should trigger a recheck.

**Comment by SpamapS** [comment]
recheck

**Comment by SpamapS** [comment]
Oops, guess we changed it so the comment has to be _only_ the word recheck. ;) It's going now.

**Comment by p-alik** [comment]
thanks

**Pull request merged**
