### PR TITLE
Add /* fall-thru */ to get rid of compiling fall through warnings

### PR DESCRIPTION
**Pull request by illuusio**
As mentioned in PR #193 there is several fall through warnings that needs to be addressed and fixed

### CODE REVIEW

**Comment by illuusio** [comment]
Yes I have to check what break before this can get in.

**Comment by esabol** [comment]
Here's what I suggest:

Undo the change the change to instance.cc here:
https://github.com/gearman/gearmand/pull/195/files#diff-b5a7d9a05aa041d6c96c67a5594f3878

That will trigger a new Travis CI build, which should pass. Once that is confirmed, then commit the change to instance.cc again to do another build, and we'll see what happens.

**Comment by illuusio** [comment]
Ok I reverted that instance.cc one and let's see if anything breaks.

**Comment by illuusio** [comment]
I have to take look that jamming test tomorrow

**Comment by esabol** [comment]
Ah, I was wrong about that break in server.cc not having any consequence. I thought it was right after a return, so it had no consequence. But that return is in an if block and the code is clearly designed to fall through to the next case. So that break is simply wrong and shouldn't go there.

**Comment by illuusio** [comment]
These switch are really done in jedi way i.e. I don't like that case drops through to another but I think we'll just don't do anything to them because they work and that warning PR go in.

**Comment by esabol** [comment]
> These switch are really done in jedi way...

Indeed. The Force is strong in this code.... 😄

**Comment by illuusio** [comment]
Yes I think I'll do that and work then to something better in distant future

**Comment by p-alik** [comment]
@SpamapS, should the PR be merged?
I'm not sure the code should be changed widely for comments matter only. In particular  changes on `libhashkit/jenkins.cc` and `libhashkit/murmur3.cc` could cause some difficulties by reviewing history of vcs.
Wouldn't be a set of proper issues a better strategy?

**Comment by illuusio** [comment]
@p-alik Yes I would like to solve those fall-through better but most of them requires heavy tests to make sure they don't break.

**Comment by illuusio** [comment]
Sorry to be away for a while. Should I break these on smaller PRs and then decide one by

**Comment by esabol** [comment]
I’m happy with the changes as they are and see no reason not to merge.

**Comment by esabol** [comment]
Could someone please merge this PR? All it does is add comments which silence gcc-8 warnings. I'm tired of seeing them.

**Comment by SpamapS** [comment]
I actually think these comments make the code more readable and clear. I don't mind messing with libhashkit either. Thanks for the thorough review and the patch!

**Comment by illuusio** [comment]
Is there upstream for hashkit anymore? I could commit a patch for them.

**Pull request merged**
