### PR TITLE
decrement server_job->function->job_total only if it > 0

### LINKED ISSUE #301: GearmanD hangs intermittantly
Hello!,

We've recently upgraded to OMD3.30 which has replaced the ancient gearmand 0.33 that was shipped previously with 1.1.19.
This includes mod-gearman (for naemon) and pnp_gearman_worker (for pnp4nagios).  We find that periodically all our naemon checks stop responding. At the same time when gearman_top is executed, we get an error:

```
failed to connect to address localhost and port 4730: Interrupted system call
```

We replaced the build of gearmand with one with symbols in it, waited for the problem to occur (about 15-20 minutes) in our setup and found that gearmand seems to be in an infinite loop here:
https://github.com/gearman/gearmand/blob/master/libgearman-server/job.cc#L399-L417

It looks like `noop_sent` is never getting incremented as it is 0 and then it's never getting into the `if` so it's never sending the `noop` to any worker and then is stuck forever.

image

### PR DESCRIPTION
**Pull request by p-alik**
The PR aims to fix #301. My tests are based on https://github.com/gearman/gearmand/issues/301#issuecomment-675059023

### CODE REVIEW

**Comment by esabol** [comment]
I was considering this same change.

Sometime between last week and today, I seem to have lost the ability to restart gearman/gearmand builds in Travis CI. Anyone know why?

**Comment by infraweavers** [comment]
This doesn't seem to have completely solved the problem we mentioned in https://github.com/gearman/gearmand/issues/301#issuecomment-675924682 however like we said before, it's possible this a completely different thing. It now takes 2 runs of the worker than doesn't timeout to force gearmand to close: 

W0wsQHOriJ

**Comment by esabol** [comment]
Well, you could add similar guards wherever job_running is decremented. There are only two locations:

https://github.com/gearman/gearmand/blob/e2d76cf631414964decc2f22006a666e1c0e2424/libgearman-server/job.cc#L301
https://github.com/gearman/gearmand/blob/e2d76cf631414964decc2f22006a666e1c0e2424/libgearman-server/job.cc#L385

But I suspect gearmand will still hang. Could you try that, @infraweavers ?

**Comment by p-alik** [comment]
> Well, you could add similar guards wherever job_running is decremented.

I did it yesterday, but the result wasn't much better:-(

> There are only two locations:
> 
> https://github.com/gearman/gearmand/blob/e2d76cf631414964decc2f22006a666e1c0e2424/libgearman-server/job.cc#L301

a1873eacd2527aeff88ea055164704f0b973175f

> 
> https://github.com/gearman/gearmand/blob/e2d76cf631414964decc2f22006a666e1c0e2424/libgearman-server/job.cc#L385

968e2836572a87a8002483a8d4991741096fe765

**Comment by infraweavers** [comment]
THis PR does at least seem to stop the `jobs_running` column from going negative in mini-test

**Comment by SpamapS** [comment]
Going to close this, but feel free to ping / re-open if you can add a regression test. I am still thinking there's something deeper and this is just treating the symptom.

**Comment by infraweavers** [comment]
Yeah sounds good

**Pull request closed without merging**
