### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gitHusband**
When I run `gearmand -v`, I got an error:

`gearmand: unrecognised option '-v'`

I think that should be changed to 'gearmand -d'

### CODE REVIEW

**Review by p-alik — COMMENTED** [review]
LGTM. But personally I would prefer to remove `-d` because it's optional.

**Comment by gitHusband** [comment]
Ok, I'll close the pull request

**Comment by p-alik** [comment]
@gitHusband, wait a bit please!

**Comment by esabol** [comment]
`-v` was [deprecated  in January, 2012](https://github.com/gearman/gearmand/commit/2f66c19873625a98da164dc5691aeef2aea5a7a8). It’s hard to believe this has been wrong for so many years!

The next paragraph says, “This will start it while printing some verbose messages.” Therefore, I think what we want here is `gearmand --verbose INFO`. @gitHusband: Would you make that change please?

**Comment by gitHusband** [comment]
@esabol Yeah, my pleasure! Changed to `gearmand --verbose INFO` now.

**Comment by esabol** [comment]
LGTM. @p-alik: Do you approve?

**Review by p-alik — APPROVED** [review]

**Pull request merged**
