### PR TITLE
Revisions to README.md

### PR DESCRIPTION
**Pull request by esabol**
Fixed typos and punctuation. Revised Contributing section for clarity.

### CODE REVIEW

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/gate_github/gearman/gearmand/85/1490462856.65/bonnyci-run-gate : FAILURE in 10m 13s

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by SpamapS** [comment]
Apologies, subscribers, for the spam. We seem to have found a bug in BonnyCI. Hopefully fixed soon.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/85/1490466908.94/bonnyci-run-check : FAILURE in 10m 11s

**Comment by SpamapS** [comment]
gate-recheck

**Comment by SpamapS** [comment]
recheck

**Comment by SpamapS** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/85/1490650955.42/bonnyci-run-check : FAILURE in 10m 37s

**Comment by SpamapS** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/85/1490652156.33/bonnyci-run-check : FAILURE in 10m 26s

**Comment by esabol** [comment]
Is there anything I need to do here?

**Comment by SpamapS** [comment]
gate-recheck

**Comment by SpamapS** [comment]
recheck

**Comment by SpamapS** [comment]
hey @esabol if you see check_github failed, you can do 'recheck'. If you see 'gate_github' fail, you can do 'gate-recheck'. Thanks for pinging me, I went ahead and did the recheck.

**Pull request merged**
