### PR TITLE
Fix bonnyci path

### PR DESCRIPTION
**Pull request by SpamapS**

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/89/1490114530.5/bonnyci-run-check : FAILURE in 41s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/89/1490114902.66/bonnyci-run-check : FAILURE in 41s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/89/1490115071.03/bonnyci-run-check : FAILURE in 34s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/gearman/gearmand/89/1490115291.95/bonnyci-run-check : FAILURE in 57m 27s

**Comment by SpamapS** [comment]
recheck

**Pull request merged**
