### PR TITLE
fixed bug which prevents whitespace in the job unique id

### PR DESCRIPTION
**Pull request by shadyb**
Fixes bug discussed in https://github.com/gearman/gearmand/issues/216

### CODE REVIEW

**Comment by esabol** [comment]
I was hoping to see `sscanf` usage removed completely. I thought that’s what we had agreed...

**Comment by p-alik** [comment]
https://github.com/gearman/gearmand/issues/216#issuecomment-442525116
> Any idea how the issue could be reproduced?

**Comment by p-alik** [comment]
OK, PR solves #216. Thank you, @shadyb! 

Tested manually with
```
#include <stdio.h>
#include <iostream>
#include <vector>

#define GEARMAN_FUNCTION_MAX_SIZE 512
#define GEARMAN_MAX_UNIQUE_SIZE 64

int main() {

    std::string queue_prefix{"gear_"};
    std::vector<std::string> elements{queue_prefix + "-testfunc-4beec2dc-f32f-11e8-aad5-7446a09167b1", queue_prefix + "-testfunc-4beec2dc f32f 11e8 aad5 7446a09167b1"};

    for (size_t x= 0; x < elements.size(); x++) {
        char* prefix= (char*) malloc(queue_prefix.size() * sizeof(char));
        char function_name[GEARMAN_FUNCTION_MAX_SIZE];
        char unique[GEARMAN_MAX_UNIQUE_SIZE];

        char fmt_str[100] = "";
        int fmt_str_length= snprintf(fmt_str, sizeof(fmt_str), "%%%d[^-]-%%%d[^-]-%%%d[^*]", // "%%%d[^-]-%%%d[^-]-%%%ds",
                                 int(queue_prefix.size()),
                                 int(GEARMAN_FUNCTION_MAX_SIZE),
                                 int(GEARMAN_MAX_UNIQUE_SIZE));

        if (fmt_str_length <= 0 or size_t(fmt_str_length) >= sizeof(fmt_str)) {
            std::cerr << "snprintf() failed to produce a valud fmt_str for redis key" << std::endl;
            break;
        }

        std::cout << "elements[" << x << "]: " << elements[x] << std::endl;

        int ret= sscanf(elements[x].c_str(),
                    fmt_str,
                    prefix,
                    function_name,
                    unique);
        free(prefix);

        if (ret == 0) {
            std::cerr << "sscanf returns 0 => skip elements[" << x << "]: " << elements[x] << std::endl;
            continue;
        }

        std::cout << "function_name: '" << function_name << "'"
                  << std::endl
                  << "unique: '" << unique << "'"
                  << std::endl;
    }

    return 0;
}
```

```
elements[0]: gear_-testfunc-4beec2dc-f32f-11e8-aad5-7446a09167b1
function_name: 'testfunc'
unique: '4beec2dc-f32f-11e8-aad5-7446a09167b1'
elements[1]: gear_-testfunc-4beec2dc f32f 11e8 aad5 7446a09167b1
function_name: 'testfunc'                                                                                                 
unique: '4beec2dc f32f 11e8 aad5 7446a09167b1' 
```

In case of old format `"%%%d[^-]-%%%d[^-]-%%%ds"` second unique contains only unique: '4beec2dc'

**Comment by esabol** [comment]
The test should be added to the test suite. I’d still like to see `sscanf` eliminated.

**Comment by p-alik** [comment]
> The test should be added to the test suite. I’d still like to see `sscanf` eliminated.

Indeed, if we'll spend time it plugins improvement the code should be written in testable manner.

**Pull request merged**
