### PR TITLE
Fix wrong printf params and crush gearman

### LINKED ISSUE #168: Gearmand crash after add some tasks
Hello.
I have the same error.
Tried to install gearman using default apt repo, and build from source.
When i add new tasks, gearmand crash with error:
```
Begin stack trace, frames found: 7
?0  0x55ef2fbb04b2 in /app/gearmand-server(+0x1f4b2) [0x55ef2fbb04b2]
?1  0x55ef2fb9f156 in /app/gearmand-server(+0xe156) [0x55ef2fb9f156]
?2  0x7fe0d7a1a390 in /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7fe0d7a1a390]
#3  0x55ef2fbbb4e2 in gearman_server_run_command at /app/gearmand-server
?4  0x55ef2fbb4ae8 in /app/gearmand-server(+0x23ae8) [0x55ef2fbb4ae8]
?5  0x7fe0d7a106ba in /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fe0d7a106ba]
#6  0x7fe0d6b2441d in clone at /lib/x86_64-linux-gnu/libc.so.6
```

How i build from source:
```
Clear ubuntu 16:04
Install:
      - curl
      - git
      - build-essential
      - libtool
      - automake
      - libboost-all-dev
      - gperf
      - libevent-dev
      - uuid-dev
      - python-sphinx

And then:
      cd /app
      git clone https://github.com/gearman/gearmand
      cd gearmand
      git checkout tags/1.1.18
      ./bootstrap.sh autoreconf
      ./configure
      make
      make install
      cp gearmand/gearmand /app/gearmand-server
      cd /app
      rm -rf /app/gearmand
```

What i am doing wrong?

Run command:
```
/app/gearmand-server --log-file "stderr"
```

### PR DESCRIPTION
**Pull request by mastanggt**
Fix #168

### CODE REVIEW

**Comment by esabol** [comment]
I would also move these three debug lines to after the ```if (server_job == NULL) {``` line to protect against possibly dereferencing a null pointer. What do you think?

**Comment by p-alik** [comment]
[#168](https://github.com/gearman/gearmand/issues/168#issuecomment-418142260) contains worker/client implementations to reproduce the issue.

**Comment by esabol** [comment]
@mastanggt, the requested changes are very minor. Could you please see this PR though to the finish line?

**Comment by esabol** [comment]
PR #183 addresses this in a better way, and it has been merged. So I think we can close this PR (without merging) now.

**Pull request closed without merging**
