### PR TITLE
added apt-get for some reqs in ubuntu

### PR DESCRIPTION
**Pull request by sfinktah**

### CODE REVIEW

**Comment by esabol** [comment]
I remember when I first tried to compile gearmand and figuring out what packages needed to be installed was annoyingly not documented, so I'm sympathetic, but I feel the Dockerfiles in PR #327 is a better solution to this problem, overall. The Dockerfile for Ubuntu in that PR contains a packages list that more complete, and there are Dockerfiles for other Linux distributions as well.

**Comment by esabol** [comment]
Also, why `libboost1.71-all-dev` and not `libboost-all-dev`? Did they make some kind of incompatible change that we're not aware of?

**Comment by sfinktah** [comment]
> Also, why `libboost1.71-all-dev` and not `libboost-all-dev`? Did they make some kind of incompatible change that we're not aware of?

Not at all, I just didn't know the generic name.  I'm all in favour of using the better information that is stored in the docker file, but since I'm totally not going to use docker, I think it might be helpful to have a suggestive link to said docker files. I will have a brief hunt for them now, and see if I can't automate something.

**Comment by esabol** [comment]
OK, this is looking better. Thanks. Please remove tcsh and wget. Wget is used to build the image in the Dockerfile to download the source code, but it's not required when building from source when you already have the source code. And tcsh is not required to build either. I should probably remove it from the Dockerfiles. I just included it in my Docker images because I'm (very) old school and prefer it as my shell. :smile:

**Comment by esabol** [comment]
Also, I think maybe you should just replace `satisfied on Ubuntu 20.04` with `satisfied on Ubuntu` because I'm pretty sure that list is the same for any version of Ubuntu going back to 16 at least and it'll probably (hopefully) work with future versions of Ubuntu, too.

**Review by SpamapS — CHANGES_REQUESTED** [review]
Hi! Thanks so much for the contribution! Can you move this to docs/source/build/ubuntu.rst and instead if you could reference that directory in the README that would be ideal so that we make space for any build env.

**Comment by sfinktah** [comment]
@esabol 

Ubuntu 20.04 changed to Ubuntu and tcsh and wget removed from packages.

@SpamapS 

With respect, moving the information to a seperate file would not be adventageous at this point.  Also, people using debian or pretty much any other packaging system can derive the needed packages from that list.

**Pull request merged**
