### PR TITLE
Add riscv64 support

### PR DESCRIPTION
**Pull request by haomi123**
Add riscv64 support

### CODE REVIEW

**Comment by esabol** [comment]
Hello, @haomi123. Thank you for your contribution. Have you successfully built gearmand on riscv64 hardware with only this minor change?

**Comment by haomi123** [comment]
> Hello, @haomi123. Thank you for your contribution. Have you successfully built gearmand on riscv64 hardware with only this small change?

Yes, I successfully built gearmand on riscv64 hardware

**Comment by esabol** [comment]
> Yes, I successfully built gearmand on riscv64 hardware

That's great! Thank you!

**Comment by SpamapS** [comment]
Thanks for merging Ed. I think we should make a minor release, there's been
a few little improvements of late. I'll work on it this weekend.

**Comment by esabol** [comment]
> Thanks for merging Ed. I think we should make a minor release, there's been a few little improvements of late. I'll work on it this weekend.

Sounds good, @SpamapS ! Thanks!

**Comment by SpamapS** [comment]
Well the weekend got away from me as they commonly do. But, it's on my list
for this coming weekend.

**Pull request merged**
