### PR TITLE
Fix dist-rpm building to work with new versioning system

### PR DESCRIPTION
**Pull request by illuusio**
This one fixes issue #148

### CODE REVIEW

**Comment by SpamapS** [comment]
Thanks! Any chance you could follow this up with a Travis test that would ensure this build keeps working? Perhaps using this: https://docs.travis-ci.com/user/deployment/packagecloud/

**Comment by esabol** [comment]
Just wondering why you removed README.md from the list of files?

**Comment by illuusio** [comment]
README.md ain't currently in installed files so it's not in source.tar.gz.

**Comment by illuusio** [comment]
@SpamapS Sure I can do test. Do Gearman has packagecloud.io account or do you just want to build rpm? I take a look at this. First would be nice to have rpm build everytime.

**Pull request merged**
