### PR TITLE
Support building with clang

### PR DESCRIPTION
**Pull request by esabol**
* Add clang-4.0 and clang-5.0 builds to Travis CI.
* Resolve clang compilation errors noted in issue #220.

### CODE REVIEW

**Comment by esabol** [comment]
Travis CI also supports building with clang 3.6, 3.7, 3.8, and 3.9. 3.6-3.8 use precise instead of trusty. 3.9 uses trusty. Do we want any of those older versions added?

https://docs.travis-ci.com/user/languages/cpp/#clang

**Comment by p-alik** [comment]
> Do we want any of those older versions added?

No I would say, unless there is a particular reason to do that.

**Comment by esabol** [comment]
> > Do we want any of those older versions added?
> 
> No I would say, unless there is a particular reason to do that.

The only reason would be to ensure support for a broader range of clang versions (and thus macOS versions). I kind of wish I had added 3.9 since that would have been trivial.

**Comment by p-alik** [comment]
The probability some of the unreliable tests fails in Travis CI is the only my worry. It would be great we improve implementation of tests at first.

**Pull request merged**
