### PR TITLE
solution for issues 176 and 177

### PR DESCRIPTION
**Pull request by p-alik**
PR aims to solve build's failure if debug enabled.
For more information see #176, #177.

### CODE REVIEW

**Comment by illuusio** [comment]
As I understand correctly this turns on UndefinedBehaviorSanitizer (-fsanitize=undefined) I understand why this is good but can't see is it somehow needed for debug? Why C++11 for Debug? Why not have C++11 for normally ad this compiles with C++0x which is same as C++11 but doesn't use all standard stuff. Also topic is little bit uninformative..

**Comment by p-alik** [comment]
> As I understand correctly this turns on UndefinedBehaviorSanitizer (-fsanitize=undefined) I understand why this is good but can't see is it somehow needed for debug?

yes. [comment on 177](https://github.com/gearman/gearmand/issues/177#issuecomment-433534601)

> Why C++11 for Debug? Why not have C++11 for normally ad this compiles with C++0x which is same as C++11 but doesn't use all standard stuff. Also topic is little bit uninformative..

The PR aims to solve the only two aforementioned issues. I my opinion we have to take over C+11 separately, because with this circumstance much more work have to be done.

**Comment by illuusio** [comment]
Ok now I understand the reasons it was TL;DR for the first time. Getting C++11 correct for old stuff is pain.

**Comment by esabol** [comment]
Would it be possible to add an `echo` to the end of `configure` output which informs/reminds user to execute gearmand with `-threads 0` when `--enable-debug` is specified?

**Comment by esabol** [comment]
Does this also fix issue #146?

**Comment by p-alik** [comment]
> Does this also fix issue #146?

yes, I would say

**Comment by p-alik** [comment]
> Would it be possible to add an echo to the end of configure output which informs/reminds user to execute gearmand with --threads 0 when --enable-debug is specified?

Would it be OK so?
https://github.com/gearman/gearmand/pull/186/commits/20341d75ef21349883d0132f3591486490880a2a

**Comment by esabol** [comment]
Ideally, I think it should be printed if and only if `--enable-debug` is actually specified.

I would recommend a blank line before the message also, in order to separate it and make it stand out more, and there should be a period at the end of the sentence.

**Comment by esabol** [comment]
I'm sorry to keep nit-picking... Technically, you have it as part of the configuration summary, which isn't right. I think you should move it down a couple lines (after the `echo "---"`), and preface the message with "NOTE: ", like the FreeBSD note below it. Maybe add some asterisks around it, again like the FreeBSD note.

Also, `echo -e` isn't portable to non-Linux systems, I think. Recommend using `printf` Instead. Reference: https://stackoverflow.com/questions/11530203/what-is-more-portable-echo-e-or-using-printf
https://stackoverflow.com/questions/11530203/what-is-more-portable-echo-e-or-using-printf
https://stackoverflow.com/questions/11530203/what-is-more-portable-echo-e-or-using-printf
https://stackoverflow.com/questions/11530203/what-is-more-portable-echo-e-or-using-printf
https://stackoverflow.com/questions/11530203/what-is-more-portable-echo-e-or-using-printf
https://stackoverflow.com/questions/11530203/what-is-more-portable-echo-e-or-using-printf

**Comment by esabol** [comment]
LOL, I would have put the asterisks before the "NOTE:", but whatever! Looks fine.

**Comment by esabol** [comment]
Actually, the `printf` needs a `\n` at the end. I also don't think we need `\n\n` at the beginning. One blank line is sufficient.

**Comment by p-alik** [comment]
new attempt to format `--enable-debug` note in  [FreeBSD style](https://github.com/gearman/gearmand/blob/a778fee77559c844317f28eb4b01ac0068008b36/configure.ac#L378-L384)

**Comment by p-alik** [comment]
resolve #176

**Pull request merged**
