### PR TITLE
Issue 137: Fix rpmlint  'missing-call-to-setgroups-before-setuid'

### PR DESCRIPTION
**Pull request by esabol**
Refer to issue #137.

### CODE REVIEW

**Comment by esabol** [comment]
*sigh* Clearly, I screwed something up with this pull request. Sorry. The only commit should have been https://github.com/gearman/gearmand/pull/211/commits/3c1c2e19a83f110fdf2922d2b6f493acad707d82. Is there a way to fix this or should I just close this issue and blow away my fork and start again from scratch?

**Comment by esabol** [comment]
I've tried various `git rebase` commands, and nothing has worked. Any suggestions?

**Comment by p-alik** [comment]
my remotes:
```
 $ git remote -v
esabol	https://github.com/esabol/gearmand.git (fetch)
esabol	https://github.com/esabol/gearmand.git (push)
gearman-org	https://github.com/gearman/gearmand.git (fetch)
gearman-org	https://github.com/gearman/gearmand.git (push)
origin	git@github.com:p-alik/gearmand.git (fetch)
origin	git@github.com:p-alik/gearmand.git (push)
```
I would do it in this manner:
```
git branch -D issue-137
git checkout -b gearman-org-master gearman/master
git pull
git checkout -b issue-137
git cherry-pick 3c1c2e1
git push --force-with-lease
```

**Comment by esabol** [comment]
% git branch -D issue-137
error: Cannot delete branch 'issue-137' checked out at '/path/to/my/github/gearmand'
% git checkout -b gearman-org-master gearman/master
fatal: 'gearman/master' is not a commit and a branch 'gearman-org-master' cannot be created from it

**Comment by p-alik** [comment]
I guess there is something wrong with your local repository. The CLI's work fine in my environment.

**Comment by SpamapS** [comment]
```
git remote add gearman git@github.com:gearman/gearmand
git remote add esabol git@github.com:esabol/gearmand
git fetch --all
git checkout -b issue-137-try2 --track gearman/master
git cherry-pick esabol/issue-137
git checkout -B issue-137 --track esabol/issue-137
git push -f
git branch -D issue-137-try2
```

**Comment by esabol** [comment]
I'm giving up on fixing this PR. I've opened a new PR #217 based on a new branch instead. I was able to get my master in sync to do that cleanly.

**Comment by p-alik** [comment]
because of `git cherry-pick esabol/issue-137`. You want only 3c1c2e1

**Comment by esabol** [comment]
> because of `git cherry-pick esabol/issue-137`. You want only [3c1c2e1](https://github.com/gearman/gearmand/commit/3c1c2e19a83f110fdf2922d2b6f493acad707d82)

Yeah, that makes sense. That's the `cherry-pick` syntax I used for my other two PRs, and those worked. Appending `--track gearman/master` to my `git checkout -b` commands has been _very_ helpful. Thanks, guys!

**Pull request closed without merging**
