### PR TITLE
[WIP] MASS_DO command

### PR DESCRIPTION
**Pull request by desyncr**
See #6 

Very initial approach. Feedback please.

### CODE REVIEW

**Comment by SpamapS** [comment]
Interesting. Can I suggest maybe _starting_ with a patch to PROTOCOL?

**Comment by desyncr** [comment]
Sure thing. I'll update PROTOCOL specs as soon as I can get to it.

**Comment by SpamapS** [comment]
Bump.. do you think you'll have any time to poke at this again soon? IIRC, Zuul doesn't need it anymore because of Zuul v3 not doing gearman-queue-per-job anymore. Is there any other driver of it? If not we should close this and the associated issue.

**Comment by desyncr** [comment]
I'd like to take a look at this again but I'm afraid I haven't had the time to do so. I guess we can close this now as I haven't contributed any working code as of now.

**Pull request closed without merging**
